#!/usr/bin/env ruby
#
# Switches the Rotel RA-1570 amplifier to the input specified as the
# only command-line argument, using the serial port protocol.
#
# Also turns down volume to `normal_volume` if it is more than
# `max_volume`, and switches to speakers A only if both A and B are
# active (in my case I never want to have both pairs active, so
# the only possibility of that happening is by accident, e.g.,
# someone else used the amp unaware of this).

require_relative 'rotel'
require 'timeout'

Timeout::timeout(10) do
  my_source = ARGV.first || 'pc_usb'  # The desired input source
  max_volume = 48     # Maximum allowed volume before switching
  normal_volume = 42  # Volume to set if it's initially too loud

  rotel = Rotel.new
  exit 0 unless rotel.sources.include? my_source

  source = rotel.source
  exit 0 if source == my_source

  # Do not allow both pairs of speakers active at once
  rotel.speakers = :a if rotel.speakers == :both

  # Turn down the volume before switching if it's too loud
  volume = rotel.volume
  rotel.volume = normal_volume if volume > max_volume

  attempts_remaining = 3
  while rotel.source != my_source && attempts_remaining > 0
    rotel.source = my_source
    attempts_remaining -= 1
  end
end

