#!/usr/bin/env osascript
# Prints out the state of iTunes (playing/stopped/paused).
# If iTunes is not running, does nothing.

if application "iTunes" is running then
    tell application "iTunes"
      set playerState to player state
      return playerstate
    end tell
end if
